In [1]:
import numpy as np 

In [14]:
def warp_mma_atom(c_frag, a_frag, b_frag): 
  # += modifies the existing c_frag array in memory
  c_frag += (a_frag @ b_frag)
  
def make_shared_memory_array(shape_in_atom_units, atom_shape):
  return np.empty(((shape_in_atom_units),(atom_shape))) 
  
  

In [15]:
atom_shape = (16,16)
shape_in_atom_units = (8,8)
A = make_shared_memory_array(shape_in_atom_units, atom_shape)

TypeError: 'tuple' object cannot be interpreted as an integer

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 2.34521389e+00  4.19928366e+00  4.46076747e+00 -2.18088532e+00
   3.83787481e-01 -2.69191472e+00 -5.05461024e+00  9.47264529e+00
   1.27596069e-01 -2.36044739e+00  5.18203752e-01  

In [ ]:
class tileTheory0: 
  def __init__ (self)
    """Assume A,B is row major, a 0 tiling of A, is a list <start_idx>_i, <shape>_i 
    """